name: Build
on:
  push:
    branches-ignore:
      - '**-wip'
  pull_request:

permissions:
  contents: read

jobs:
  make:
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository)
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20.20.2'
      - uses: pnpm/action-setup@v5
        with:
          run_install: |
            - recursive: true
      - name: Prepack
        run: pnpm prepack
      - name: Publish
        run: pnpm pkg-pr-new publish --package-manager=pnpm --pnpm
