name: Publish
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: npm install -g npm@latest
      - name: prepack
        run: pnpm prepack
      - name: publish
        run: npm publish
